export const callsActionTypes = {
  FETCH_CALLS: "FETCH_CALLS",
  FETCH_CALLS_SUCCESS: "FETCH_CALLS_SUCCESS",
  FETCH_CALLS_ERROR: "FETCH_CALLS_ERROR",
};
export const toggleArchiveCallTypes = {
  TOGGLE_ARCHIVE_CALL: "TOGGLE_ARCHIVE_CALL",
  TOGGLE_ARCHIVE_CALL_SUCCESS: "TOGGLE_ARCHIVE_CALL_SUCCESS",
  TOGGLE_ARCHIVE_CALL_ERROR: "TOGGLE_ARCHIVE_CALL_ERROR",
};
export const addAllToArchiveTypes = {
  ADD_ALL_TO_ARCHIVE: "ADD_ALL_TO_ARCHIVE",
  ADD_ALL_TO_ARCHIVE_SUCCESS: "ADD_ALL_TO_ARCHIVE_SUCCESS",
  ADD_ALL_TO_ARCHIVE_ERROR: "ADD_ALL_TO_ARCHIVE_ERROR",
};
export const resetArchiveTypes = {
  RESET_ARCHIVE: "RESET_ARCHIVE",
  RESET_ARCHIVE_SUCCESS: "RESET_ARCHIVE_SUCCESS",
  RESET_ARCHIVE_ERROR: "RESET_ARCHIVE_ERROR",
};
